export const serverBaseUrl = "http://10.0.2.2:3000";
export const INVALID_AGREE_MSG = "Agreement is required.";
export const INVALID_USR_MSG = "Username must conatin at least 5 characters.";
export const INVALID_PASSWORD_MSG = "Password needs to conatin at least 5 characters and one number.";
export const INVALID_EMAIL_MSG = "Invalid email.";
export const INVALID_PHONE_MSG = "Invalid phone number.";
export const INVALID_LOGIN_MSG = "Invalid username or password, please try again.";
export const REPEAT_PASSWORD_MSG = "Passwords do not match.";
export const GOOGLE_PLACES_API_KEY = "AIzaSyDLU7ME7Ck5nykTBrfNidv-w1-Uua-0dUM";
export const GOOGLE_PLACES_DETAILS_URL = "https://maps.googleapis.com/maps/api/place/details/json?place_id=";
export const LAST_NAME_MSG = "Last name is required.";
export const FIRST_NAME_MSG = "First name is required.";
export const NAME_MSG = "Name is required.";
export const CATEGORY_MSG = "Category is required.";
export const DESCRIPTION_MSG = "Description is required.";
export const INVALID_OPEN_MSG = "Invalid open time.";
export const INVALID_CLOSE_MSG = "Invalid close time.";
export const INVALID_DURATION_MSG = "Invalid duration meeting.";
export const INVALID_MAX_DATE_MSG = "Invalid max date.";
export const INVALID_OFF_DATE_MSG = "Invalid off date.";
export const ADDRESS_MSG = "Address is required.";

